## Arithmatic Function

to cheak min of array :- np.min()
    
to cheak max of array :- np.max()
    
to cheak min value's index for array :- np.argmin()
    
to cheak max value's index for array :- np.argmax()     


In [6]:
import numpy as np

var = np.array([1,7,5,8,9,3,5,6])
print("min : ",np.min(var),"  index : ",np.argmin(var) )
print("max : ",np.max(var),"  index : ",np.argmax(var) )

min :  1   index :  0
max :  9   index :  4


__________________________________________________
axis = 0 :-  coloum

axis = 1 :-  Row

In [9]:
var = np.array([[1,9,6],[6,8,9]])
print(np.min(var,axis=0))
print()
print(np.max(var,axis=1))

[1 8 6]

[9 9]


In [11]:
## Squre root
var = np.array([16,25,49])
print(np.sqrt(var))

[4. 5. 7.]


In [14]:
var  = np.array([1,3,4])
print(np.sin(var))
print()
print(np.cos(var))
print()
print(np.tan(var))

[ 0.84147098  0.14112001 -0.7568025 ]

[ 0.54030231 -0.9899925  -0.65364362]

[ 1.55740772 -0.14254654  1.15782128]


In [20]:
var  = np.array([[1,3,4],[2,6,9]])
print(var)
print(np.cumsum(var))

[[1 3 4]
 [2 6 9]]
[ 1  4  8 10 16 25]
