# Arithematic Operation

In [19]:
## For 1 D Array

import numpy as np
var = np.array([1,6,8,96,4])

varadd = (var + 3)

print(varadd)

[ 4  9 11 99  7]


In [4]:
## Addition
var1 = np.array([1,3,2,3])
var2 = np.array([1,3,2,3])

varadd = var1+var2

print(varadd)

[1 9 4 9]


In [5]:
## Substraction
var1 = np.array([1,3,2,3])
var2 = np.array([1,3,2,3])

varadd = var1-var2

print(varadd)

[0 0 0 0]


In [6]:
## multiplication
var1 = np.array([1,3,2,3])
var2 = np.array([1,3,2,3])

varadd = var1*var2

print(varadd)

[1 9 4 9]


In [11]:
## Division
var1 = np.array([1,3,2,3])
var2 = np.array([1,3,2,3])
varadd = var1/var2
print(var1.dtype)
print(varadd)
print(varadd.dtype)

int32
[1. 1. 1. 1.]
float64


## Arithematic Operation by  Functions()

 Addition  :-       np.add(a,b)
 
 Substraction :-    np.subtract(a,b)
 
 multiplication :-   np.multiply(a,b)
 
 Division :-          np.divide(a,b)
 
 Modulus :-        np.mod(a,b)
 
 power :-           np.power(a,b)
 
 
 Reciprocal :-     np.reciprocal(a)

In [13]:
## Addition
var1 = np.array([1,3,2,3])
var2 = np.array([1,3,2,3])

varadd = np.add(var1,var2)

print(varadd)

[2 6 4 6]


In [15]:
## Substaction
var1 = np.array([1,3,2,3])
var2 = np.array([1,3,2,3])

varsub = np.subtract(var1,var2)

print(varadd)

[0 0 0 0]



## For 2D Array


In [21]:
var1 = np.array([[1,3,2,3],[2,4,6,7]])
var2 = np.array([[1,3,2,3],[2,4,6,7]])

varadd = var1+var2

print(varadd)

[[ 2  6  4  6]
 [ 4  8 12 14]]


In [22]:
var1 = np.array([[1,3,2,3],[2,4,6,7]])
var2 = np.array([[1,3,2,3],[2,4,6,7]])

varadd = np.add(var1,var2)

print(varadd)

[[ 2  6  4  6]
 [ 4  8 12 14]]


In [26]:
a = np.array([1,4,6,1])

var = np.reciprocal(a)
print(var)

[1 0 0 1]
