## Search

In [2]:
import numpy as np

In [4]:
var = np.array([1,2,3,4,5,6,7,8,9,11,12,13,2,14,15,16,17])

print(np.where(var == 2)) ## this will give the output element index and Datatype

(array([ 1, 12], dtype=int64),)


In [12]:
var = np.array([1,2,3,4,5,6,7,8,9,11,12,13,2,14,15,16,17])
print(np.where(var % 2 == 0))

(array([ 1,  3,  5,  7, 10, 12, 13, 15], dtype=int64),)


# search sorted Array

this will search for the postion where given element is to be placed

In [26]:
var_1 = np.array([1,2,3,5,6,7,8])
a  = np.searchsorted(var_1 , 9, side="right")
print(a)
print(var)

7
[1 2 3 5 6 7 8]


## Sorting of array

In [27]:
var2 = np.array([6,9,65,3,45,7,9,6,43,5,7,8,56,45,77,56])  ## Integer
print(np.sort(var2))

[ 3  5  6  6  7  7  8  9  9 43 45 45 56 56 65 77]


In [28]:
var_2 = np.array(["sdaf","sdrff","asdfwf","wewefdf",])  ## String
print(np.sort(var_2))

['asdfwf' 'sdaf' 'sdrff' 'wewefdf']


In [31]:
var2 = np.array([[6,9,65,89],[3,45,7,9],[6,43,5,7],[56,45,77,56]])  ## 2D Array
print(np.sort(var2))

[[ 6  9 65 89]
 [ 3  7  9 45]
 [ 5  6  7 43]
 [45 56 56 77]]


## Filter Array

In [33]:
var5 = np.array(["a","b","c","d"])
y =           [True,False,True,False] 

var6 = var5[y]
print(var6)
print(type(var6))

['a' 'c']
<class 'numpy.ndarray'>
