# Array

In [5]:
import numpy as np 
a  = np.array([1,2,5,6])
print(a)
print(type(a))

[1 2 5 6]
<class 'numpy.ndarray'>


Take user input and make array

In [10]:
l = []
for i in range (1,5):
    int_1 = int(input("Enter : "))
    l.append(int_1)
print(np.array(l))

Enter : 4
Enter : 5
Enter : 7
Enter : 3
[4 5 7 3]


Types of Array : 

1D array

2D array 

3D array

High Dimensional Array

to find the dimension use {ndim}

2d Array :-

In [13]:
arr2 = np.array([[1,46,3,56,],[4,5,7,3]])
print(arr2)
print(arr2.ndim)

[[ 1 46  3 56]
 [ 4  5  7  3]]
2


3d Array :-

In [16]:
arr3 = np.array([[[2,5,3],[6,8,3],[4,6,8]]])
print(arr3)
print(arr3.ndim)

[[[2 5 3]
  [6 8 3]
  [4 6 8]]]
3


N dimensional Array :-

 max limit of    [ndmin]   is 32 mins by ndmin we can only create          [32 Dimensional array]

In [20]:
arn = np.array([3,5,7,5],ndmin = 32)
print(arn)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[3 5 7 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


# Special Type of Array

Array filled with 0


Array filled with 1


Empty array


An Array with range element 


Array digonal element filled with 1


create Array with Special interval



## Array filled with Zero 

In [3]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array filled with 1

In [7]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Empty Array 

empty array contains data of the previous array when we print it

In [5]:
ar_em = np.empty(4)
ar_em1 = np.empty((3,4))
print(ar_em)
print()
print(ar_em1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Range Array

we use np.arrange in the range array 

In [10]:
ar_rn = np.arange(4,8)
print(ar_rn)
ar_rn1 = np.arange(5)
print(ar_rn1)

[4 5 6 7]
[0 1 2 3 4]


## Array with digonal element filled with 1

Identity matrix

np.eye use to create the digonal Array



In [11]:
ar_di = np.eye(3)
print(ar_di)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ar_di = np.eye(3,5)
print(ar_di)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## lineSpace

In [17]:
ar_ls = np.linspace(0,20,num=5)
print(ar_ls)

[ 0.  5. 10. 15. 20.]


In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 3])

2nd element on 1st row:  9


In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


## Random no.

rand() :- this function genrate value between  0 to 1

randn() :- this function genrate the value closer to the 0 . and the value will be positive or negative

ranf() :- this function genrate the value between 0.0 to 1.0 .but this function  doesnot include the 1.0 

          this is half open function
          
randint() :- this function genrate the value between given no. 



In [25]:
## RAND() Function
## 1D 
var = np.random.rand(6)
print(var)

[0.37645041 0.33093688 0.34861051 0.01085619 0.55761067 0.59296141]


In [26]:
var1  = np.random.rand(2,3)
print(var1)

[[0.95404782 0.61090852 0.8953352 ]
 [0.74490766 0.98757833 0.52467204]]


In [29]:
## randn()
var2 = np.random.randn(5)  ## 1D
var_2 = np.random.randn(2,3) ## 2D
print(var2)
print()  
print(var_2)

[-1.65717144 -1.44912463 -0.40323867  0.41025486 -0.30461848]

[[-1.0262887  -1.35986451  1.18576703]
 [ 2.24714242 -0.83833935  0.29088918]]


In [35]:
## ranf()
var3 = np.random.ranf(5)## 1D
var_3 = np.random.ranf((2,3)) ## 2D
print(var3)
print()
print(var_3)

[0.02234546 0.3461326  0.778974   0.11833608 0.6161757 ]

[[0.75123991 0.31376442 0.80475481]
 [0.91110034 0.43741441 0.62164164]]


In [44]:
 ## randint()
var4  = np.random.randint(5,100,3) ## 1 D 
var_4 = np.random.randint(5,100,(2,3)) ## 2D
print(var4)
print()
print(var_4)

[56 89 67]

[[21 16 23]
 [94 94 89]]
