## Shuffle

In [8]:
import numpy as np

In [11]:
var = np.array([1,2,3,4,5,6])
np.random.shuffle(var)
print(var)

[6 5 2 4 1 3]


## unique

In [33]:
np.random.seed(12)
var = np.array([1,1,2,2,3,3,6,5,45,8,8,45,745,85,])
x = np.unique(var,return_counts=True) ## unique is likke set it will not repet the value and give ubiqye data
                                            ## and Return_count will give the how many times it had repeted
print(x)

(array([  1,   2,   3,   5,   6,   8,  45,  85, 745]), array([2, 2, 2, 1, 1, 2, 2, 1, 1], dtype=int64))


In [34]:
np.random.seed(17)
var = np.array([x for x in np.random.randint(10, 90, 10)])
var

array([25, 16, 32, 67, 55, 32, 41, 78, 49, 54])

## Resize

In [39]:
var2= np.array([1,2,6,8,8,5,5,47,6])

y = np.resize(var2,(3,2))
print(y)

[[1 2]
 [6 8]
 [8 5]]


## flatten & Ravel

In [45]:
var2= np.array([1,2,6,8,8,5,5,47,6])
y = np.resize(var2,(3,3))
print(y)
print()
print(y.flatten())
print()
print(np.ravel(y))

[[ 1  2  6]
 [ 8  8  5]
 [ 5 47  6]]

[ 1  2  6  8  8  5  5 47  6]

[ 1  2  6  8  8  5  5 47  6]
