# Brodcasting in Numpy

 # Some Rules while performing Operation
 
 1) Same Dimensions
 
 2) from both Atleast one have containing 1 in their Dimensions

In [1]:
import numpy as np

In [14]:
var1 = np.array([1,2,3])
print(var1)
print()
print(var1.shape)
print()
var2 = np.array([[1],[2],[3]])
print(var2)
print()
print(var2.shape)

x = np.add(var1,var2)
print()
print(x)

[1 2 3]

(3,)

[[1]
 [2]
 [3]]

(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
