In [1]:
import numpy as np

In [4]:
var = np.matrix([[1,2],[3,4]])
var2 = np.matrix([[1,2],[3,4]])  ## Creating Matrix

print(var*var2)   ##  performing  arithematic operation
print()
print(var.dot(var2)) ## multiplication using .dot function
print()
print(var+var2)
print()

print(var-var2)


[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]

[[2 4]
 [6 8]]

[[0 0]
 [0 0]]


## Matrix function

 Transpose :- in this matrix change the axis means 2*3  converted in to 3*2
 
 

In [7]:
var3 = np.array([[2,4,56],[5,6,78]])

print(var3)
print()

print(np.transpose(var3))
print()
print(var3.T)

[[ 2  4 56]
 [ 5  6 78]]

[[ 2  5]
 [ 4  6]
 [56 78]]

[[ 2  5]
 [ 4  6]
 [56 78]]


Swapaxes :- 

In [9]:
var4 = np.array([[2,4,56],[5,6,78]])

print(var4)
print()
print(np.swapaxes(var4,0,1))

[[ 2  4 56]
 [ 5  6 78]]

[[ 2  5]
 [ 4  6]
 [56 78]]


Inverse Matrix : - 

In [12]:
var5 = np.array([[2,4],[5,6]])
print(var5)
print()
print(np.linalg.inv(var5))

[[2 4]
 [5 6]]

[[-0.75   0.5  ]
 [ 0.625 -0.25 ]]
