# Data type in Numpy Array

In [2]:
import numpy as np

var = np.array([1,2,6,9,8])

print("Datatypr : ",var.dtype)


Datatypr :  int32


In [3]:
import numpy as np

var = np.array([1.2,2,6,9,8])

print("Datatypr : ",var.dtype)


Datatypr :  float64


In [4]:
var = np.array(["a","r"])

print("Datatypr : ",var.dtype)

Datatypr :  <U1


In [5]:
var = np.array([1.2,2,"s"])

print("Datatypr : ",var.dtype)

Datatypr :  <U32


## How To Change The Datatype

In [9]:
x = np.array([1,2,3,4],dtype =np.int8)

print("Data Type : ",x.dtype)

Data Type :  int8


In [11]:
x1 = np.array([1,2,3,4],dtype ="f")

print("Data Type : ",x1.dtype)
print(x1)

Data Type :  float32
[1. 2. 3. 4.]


Change Datatype by function 

In [15]:
x2 = np.array([1,2,3,4],)
new = np.float32(x2)
new_1 = np.int32(new)
print("Data Type : ",x2.dtype)
print(x2)
print("Data Type : ",new.dtype)
print(new)
print("Data Type : ",new_1.dtype)
print(new_1)

Data Type :  int32
[1 2 3 4]
Data Type :  float32
[1. 2. 3. 4.]
Data Type :  int32
[1 2 3 4]


In [16]:
x3 = np.array([1,6,8,6,9])
new = x3.astype(float)

print(x3)
print(new)

[1 6 8 6 9]
[1. 6. 8. 6. 9.]
