## Insert

While we inserting the data the data must be in integer format

if data in float value it will automatically converted in to integer

In [2]:
import numpy as np

In [4]:
var = np.array([1,2,3,4,5])
print(var)
print()
v= np.insert(var,2,40)    ## inserting data in the array
print(v)

[1 2 3 4 5]

[ 1  2 40  3  4  5]


In [7]:
var = np.array([1,2,3,4,5])
print(var)
print()
v= np.insert(var,(2,4),(40,6.5))    ## inserting multiple data in the array  by giving index
print(v)

[1 2 3 4 5]

[ 1  2 40  3  4  6  5]


In [15]:
var1 = np.array([[1,2,5,6,4],[6,9,8,7,5]])
print(var1)                                 ## inserting Data in 2D Array
print()
v = np.insert(var1,1,3,axis=0)  ## axis = 0 means row           axis = 1 means coloum
print(v)

[[1 2 5 6 4]
 [6 9 8 7 5]]

[[1 2 5 6 4]
 [3 3 3 3 3]
 [6 9 8 7 5]]


## append Function

In [17]:
var2 = np.array([1,2,6,96,7,5,8,])

v = np.append(var2,6.5)
print(v)

[ 1.   2.   6.  96.   7.   5.   8.   6.5]


In [24]:
var3 = np.array([[2,4,5],[5,6,7]])

c = np.append(var3,[[5,6,8]],axis = 0 )
print(c)

[[2 4 5]
 [5 6 7]
 [5 6 8]]


## Deleting

In [25]:
var5 = np.array([2,2,3,4,4,])

c = np.delete(var5,3)
print(c)

[2 2 3 4]
