In [1]:
import numpy as np

In [24]:
var = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(var)
print()
for i in var : ## using for looop itreate the data
  print(i)
  for j in i :
    print(j)


[[1 2 3 4 5]
 [6 7 8 9 0]]

[1 2 3 4 5]
1
2
3
4
5
[6 7 8 9 0]
6
7
8
9
0


In [28]:
var2 = np.array([[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]]])
print(var2)
print()
for i in np.nditer(var2,flags=['buffered'],op_dtypes= ["float"]): ## use nditer function  to itrate the 3d array and convert datatype
  print(i)



[[[ 1  2  3  4  5]
  [ 6  7  8  9  0]
  [11 12 13 14 15]]]

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
0.0
11.0
12.0
13.0
14.0
15.0


In [36]:
var2 = np.array([[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]]])
print(var2)
print()
for i,d in np.ndenumerate(var2): ## ndeumerate will give the all elements indexing and also give that no.s
  print(i,d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9  0]
  [11 12 13 14 15]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 0
(0, 2, 0) 11
(0, 2, 1) 12
(0, 2, 2) 13
(0, 2, 3) 14
(0, 2, 4) 15


In [ ]:
##