## Join Array

In [4]:
import numpy as np

to join the array use :- Concatenate ((a,b))

one more function to marge array is stack

In [8]:
var = np.array([1,2,3,4,5])
var1 = np.array([6,7,8,9,0])

a = np.concatenate((var,var1))
print(a)

[1 2 3 4 5 6 7 8 9 0]


For Row along :-  axis = 1
For Coloum along : - axis = 0

In [21]:
var_0 = np.array([[1,2],[3,4]])
var_1= np.array([[6,7],[8,9]])

a = np.concatenate((var,var1),axis = 1)
print(var_0)
print()
print(var_1)
print()
print(a)

[[1 2]
 [3 4]]

[[6 7]
 [8 9]]

[[1 2 6 7]
 [3 4 8 9]]


In [20]:
var_2 = np.array([1,2,3,4,5])
var_3 = np.array([6,7,8,9,0])

a_n = np.stack((var_2,var_3), axis = 1)
print(a_n)

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


In [24]:
var_2 = np.array([1,2,3,4,5])
var_3 = np.array([6,7,8,9,0])

a_0 = np.stack((var_2,var_3), axis = 1)
a_1 = np.hstack((var_2,var_3))  ## row
a_2 = np.vstack((var_2,var_3))  ## colume
a_3 = np.dstack((var_2,var_3))  ## Height
print(a_0)
print()
print(a_1)
print()
print(a_2)
print()
print(a_3)

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]

[1 2 3 4 5 6 7 8 9 0]

[[1 2 3 4 5]
 [6 7 8 9 0]]

[[[1 6]
  [2 7]
  [3 8]
  [4 9]
  [5 0]]]


# Split Array

In [28]:
var4 = np.array([1,2,3,4,5,6,7,8,9])

print (var4)
sa = np.array_split(var4,5)
print(sa)

[1 2 3 4 5 6 7 8 9]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


In [34]:
var4 = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print (var4)
sa = np.array_split(var4,4)
print(sa)


[[1 2 3 4 5]
 [6 7 8 9 0]]
[array([[1, 2, 3, 4, 5]]), array([[6, 7, 8, 9, 0]]), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32)]
