In [1]:
import numpy as np


In [9]:
var = np.array([1,2,3,4,5,6,7,8])
            ##  0 1 2 3 4 5 6 7 
print(var)
print()
print(var[1:6]) ## specific range
print()
print(var[1:]) ## no ending given
print()
print(var[:5])##no starting given
print()
print(var[::2]) ## no starting no ending but jumping over one step

[1 2 3 4 5 6 7 8]

[2 3 4 5 6]

[2 3 4 5 6 7 8]

[1 2 3 4 5]

[1 3 5 7]


In [15]:
var2 = np.array([[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]])
print(var2)
print()
print(var2[2,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]

[12 13 14]
