# Shape

In [3]:
import numpy as np
var = np.array([[1,2],[6,5]])
print(var)
print(var.shape)

[[1 2]
 [6 5]]
(2, 2)


In [11]:
var1 = np.array([1,2,3,4],ndmin = 4)
print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


## Reshape



In [20]:
var2 = np.array([5,6,8,9,6,9])
x = var2.reshape(3,2)
print(var2)
print()
print(x)
print()
print("Dimension of var2 : ",var2.ndim,"D")
print()
print("Dimension of X : ",x.ndim,"D")


[5 6 8 9 6 9]

[[5 6]
 [8 9]
 [6 9]]

Dimension of var2 :  1 D

Dimension of X :  2 D


In [22]:
var3 = np.array([5,6,8,9,6,9,6,9,7,6,5,4])
x = var3.reshape(2,3,2)
print(var3)
print()
print(x)
print()
print("Dimension of var3 : ",var3.ndim,"D")
print()
print("Dimension of X : ",x.ndim,"D")


[5 6 8 9 6 9 6 9 7 6 5 4]

[[[5 6]
  [8 9]
  [6 9]]

 [[6 9]
  [7 6]
  [5 4]]]

Dimension of var3 :  1 D

Dimension of X :  3 D


In [32]:
var2 = np.array([5,6,8,9,6,9])  ## 1D array
x = var2.reshape(3,2) ## Convaer 1D array into 2D Array
print(var2)
print()
print(x)
print()
print("Dimension of var2 : ",var2.ndim,"D")
print()
print("Dimension of X : ",x.ndim,"D")

oneDim = x.reshape(-1) ## Again 2D Array Converted into 1D Array
print()
print(oneDim)
print()
print("Dimension of onedim : ",oneDim.ndim)

[5 6 8 9 6 9]

[[5 6]
 [8 9]
 [6 9]]

Dimension of var2 :  1 D

Dimension of X :  2 D

[5 6 8 9 6 9]

Dimension of onedim :  1
